version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: language_coach_postgres
    environment:
      POSTGRES_DB: language_coach
      POSTGRES_USER: language_coach_user
      POSTGRES_PASSWORD: language_coach_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U language_coach_user -d language_coach"]
      interval: 5s
      timeout: 5s
      retries: 5

  language_coach:
    build:
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
    ports:
      - 8000:80
    
    env_file: .env.docker

volumes:
  postgres_data: